FROM python:3.9-alpine

COPY app.py /home/

WORKDIR /home/

RUN apk update && \
    apk add --no-cache bash && \
    pip install --upgrade pip && \
    pip install uvicorn fastapi

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80"]

EXPOSE 80